/*
 *  Copyright 2009-2012 Michael Dalton
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package java.sql;

public interface Connection {

    Statement createStatement();

    PreparedStatement prepareStatement(String sql);

    CallableStatement prepareCall(String sql);

    DatabaseMetaData getMetaData();

    PreparedStatement prepareStatement(String sql, int resultSetType,
                                       int resultSetConcurrency);

    CallableStatement prepareCall(String sql, int resultSetType,
                                  int resultSetConcurrency); 

    PreparedStatement prepareStatement(String sql, int resultSetType,
                                       int resultSetConcurrency, 
                                       int resultSetHoldability);

    CallableStatement prepareCall(String sql, int resultSetType,
                                  int resultSetConcurrency,
                                  int resultSetHoldability);
    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys);

    PreparedStatement prepareStatement(String sql, int columnIndexes[]);
    
    PreparedStatement prepareStatement(String sql, String columnNames[]);
}
