/* Copyright 2009 Michael Dalton */
package java.sql;

public interface Statement {

    void close();

    ResultSet executeQuery(String sql);

    int executeUpdate(String sql);

    boolean execute(String sql);

    void addBatch(String sql);

    Connection getConnection();

    int executeUpdate(String sql, int autoGeneratedKeys);
    
    int executeUpdate(String sql, int columnIndexes[]);

    int executeUpdate(String sql, String columnNames[]);

    boolean execute(String sql, int autoGeneratedKeys);

    boolean execute(String sql, int columnIndexes[]);

    boolean execute(String sql, String columnNames[]);
}
