/*
 *  Copyright 2009-2012 Michael Dalton
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package java.sql;

public interface Statement {

    void close();

    ResultSet executeQuery(String sql);

    int executeUpdate(String sql);

    boolean execute(String sql);

    void addBatch(String sql);

    Connection getConnection();

    int executeUpdate(String sql, int autoGeneratedKeys);
    
    int executeUpdate(String sql, int columnIndexes[]);

    int executeUpdate(String sql, String columnNames[]);

    boolean execute(String sql, int autoGeneratedKeys);

    boolean execute(String sql, int columnIndexes[]);

    boolean execute(String sql, String columnNames[]);
}
