/*
 *  Copyright 2009-2012 Michael Dalton
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package jtaint.sql;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

public class MockStatement implements Statement {

    private final Connection c;

    public MockStatement(Connection c) {
        this.c = c;
    }

    public ResultSet executeQuery(String sql) {
        ResultSet r = new MockResultSet();
        sql = sql + r;
        return r;
    }

    public int executeUpdate(String sql) {
        sql = sql + sql;
        return 0;
    }

    public boolean execute(String sql) {
        sql = sql + sql;
        return true;
    }

    public void addBatch(String sql) {
        sql = sql + sql;
    }

    public Connection getConnection() {
        return c;
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) {
        sql = sql + autoGeneratedKeys;
        return 0;
    }
    
    public int executeUpdate(String sql, int columnIndexes[]) {
        sql = sql + columnIndexes;
        return 0;
    }

    public int executeUpdate(String sql, String columnNames[]) {
        sql = sql + columnNames;
        return 0;
    }

    public boolean execute(String sql, int autoGeneratedKeys) {
        sql = sql + sql;
        return true;
    }

    public boolean execute(String sql, int columnIndexes[]) {
        sql = sql + sql;
        return true;
    }

    public boolean execute(String sql, String columnNames[]) {
        sql = sql + sql;
        return true;
    }

    public void close() { }
}
